#version of docker compose
version: "3" 
#services are which containers you have.
services:
  node-app: #any name, this will be name of the app in this container
    volumes: #relative pathes
      - ./src:/app/src:ro #local path : container path : read only
    environment:
      - NODE_ENV=development #environment variable
