version: "3" 
services:
  node-app: 
    volumes: 
      #local path : container path : read only
      - ./src:/app/src:ro 
    environment:
      - NODE_ENV=development 
    command: npm run start-dev
